# Generated by Django 5.1.4 on 2025-01-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_taskhistory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='latest_version',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
